# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Program Files\QGIS 3.16\apps\qgis\python\plugins\DEM2STL-QGIS_Plugin\stl_generator_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StlGeneratorDialogBase(object):
    def setupUi(self, StlGeneratorDialogBase):
        StlGeneratorDialogBase.setObjectName("StlGeneratorDialogBase")
        StlGeneratorDialogBase.resize(377, 480)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(StlGeneratorDialogBase)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(StlGeneratorDialogBase)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layers_comboBox = QgsMapLayerComboBox(self.groupBox)
        self.layers_comboBox.setShowCrs(True)
        self.layers_comboBox.setObjectName("layers_comboBox")
        self.verticalLayout.addWidget(self.layers_comboBox)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(StlGeneratorDialogBase)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.printHeight_input = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.printHeight_input.setProperty("value", 10.0)
        self.printHeight_input.setObjectName("printHeight_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.printHeight_input)
        self.printHeight_label = QtWidgets.QLabel(self.groupBox_2)
        self.printHeight_label.setObjectName("printHeight_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.printHeight_label)
        self.baseHeight_input = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.baseHeight_input.setProperty("value", 10.0)
        self.baseHeight_input.setObjectName("baseHeight_input")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.baseHeight_input)
        self.base_label = QtWidgets.QLabel(self.groupBox_2)
        self.base_label.setObjectName("base_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.base_label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(StlGeneratorDialogBase)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_8)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(4, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        self.bedWidth_input = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.bedWidth_input.setMaximum(10000.0)
        self.bedWidth_input.setProperty("value", 200.0)
        self.bedWidth_input.setObjectName("bedWidth_input")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.bedWidth_input)
        self.bedLength_input = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.bedLength_input.setMaximum(10000.0)
        self.bedLength_input.setProperty("value", 200.0)
        self.bedLength_input.setObjectName("bedLength_input")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.bedLength_input)
        self.lineWidth_input = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.lineWidth_input.setSingleStep(0.1)
        self.lineWidth_input.setProperty("value", 0.4)
        self.lineWidth_input.setObjectName("lineWidth_input")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lineWidth_input)
        self.verticalLayout_4.addLayout(self.formLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(StlGeneratorDialogBase)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.saveLocation_input = QgsFileWidget(self.groupBox_4)
        self.saveLocation_input.setStorageMode(QgsFileWidget.GetDirectory)
        self.saveLocation_input.setObjectName("saveLocation_input")
        self.verticalLayout_5.addWidget(self.saveLocation_input)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.progress = QtWidgets.QProgressBar(StlGeneratorDialogBase)
        self.progress.setProperty("value", 0)
        self.progress.setObjectName("progress")
        self.verticalLayout_3.addWidget(self.progress)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.generateSTL_button = QtWidgets.QPushButton(StlGeneratorDialogBase)
        self.generateSTL_button.setObjectName("generateSTL_button")
        self.horizontalLayout.addWidget(self.generateSTL_button)
        self.abort_button = QtWidgets.QPushButton(StlGeneratorDialogBase)
        self.abort_button.setObjectName("abort_button")
        self.horizontalLayout.addWidget(self.abort_button)
        self.exit_button = QtWidgets.QPushButton(StlGeneratorDialogBase)
        self.exit_button.setDefault(False)
        self.exit_button.setFlat(False)
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout.addWidget(self.exit_button)
        self.horizontalLayout.setStretch(0, 12)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(StlGeneratorDialogBase)
        QtCore.QMetaObject.connectSlotsByName(StlGeneratorDialogBase)

    def retranslateUi(self, StlGeneratorDialogBase):
        _translate = QtCore.QCoreApplication.translate
        StlGeneratorDialogBase.setWindowTitle(_translate("StlGeneratorDialogBase", "STLGenerator"))
        self.groupBox.setTitle(_translate("StlGeneratorDialogBase", "Layer to Print"))
        self.groupBox_2.setTitle(_translate("StlGeneratorDialogBase", "Model Settings"))
        self.printHeight_label.setText(_translate("StlGeneratorDialogBase", "Model Height (mm)"))
        self.base_label.setText(_translate("StlGeneratorDialogBase", "Base Thickness (mm)"))
        self.groupBox_3.setTitle(_translate("StlGeneratorDialogBase", "Printer Settings"))
        self.label_6.setText(_translate("StlGeneratorDialogBase", "Bed Width (mm)"))
        self.label_7.setText(_translate("StlGeneratorDialogBase", "Bed Length (mm)"))
        self.label_8.setText(_translate("StlGeneratorDialogBase", "Line Width (mm)"))
        self.groupBox_4.setTitle(_translate("StlGeneratorDialogBase", "File Location"))
        self.generateSTL_button.setText(_translate("StlGeneratorDialogBase", "Generate STL"))
        self.abort_button.setText(_translate("StlGeneratorDialogBase", "Abort"))
        self.exit_button.setText(_translate("StlGeneratorDialogBase", "Exit"))
from qgsfilewidget import QgsFileWidget
from qgsmaplayercombobox import QgsMapLayerComboBox
