#ifndef MESHGENERATOR_GLOBAL_H
#define MESHGENERATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MESHGENERATOR_LIBRARY)
#  define MESHGENERATOR_EXPORT Q_DECL_EXPORT
#else
#  define MESHGENERATOR_EXPORT Q_DECL_IMPORT
#endif

#endif // MESHGENERATOR_GLOBAL_H
